# Generated by Django 3.1.3 on 2021-07-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etrade', '0008_auto_20210705_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='Customer',
        ),
    ]
