# Generated by Django 3.1.3 on 2021-07-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrade', '0009_auto_20210705_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='sampledata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('spath', models.IntegerField(verbose_name='')),
                ('edgeW', models.IntegerField(verbose_name='')),
                ('no_of_edge', models.IntegerField(verbose_name='')),
                ('from_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('to_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('dist', models.FloatField(verbose_name='')),
                ('sample_mean', models.FloatField(verbose_name='')),
            ],
        ),
    ]
