# Generated by Django 3.1.3 on 2021-07-06 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etrade', '0010_sampledata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampledata',
            old_name='sample_mean',
            new_name='Mean',
        ),
        migrations.RenameField(
            model_name='sampledata',
            old_name='no_of_edge',
            new_name='noOfEdges',
        ),
    ]
