# Generated by Django 3.1.3 on 2021-07-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etrade', '0011_auto_20210706_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampledata',
            old_name='spath',
            new_name='Spath',
        ),
    ]
