# Generated by Django 3.1.3 on 2021-07-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrade', '0012_auto_20210706_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
