# Generated by Django 3.1.3 on 2021-07-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etrade', '0014_auto_20210706_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledata',
            name='Spath',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='edgeW',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='noOfEdges',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
    ]
